### ISSUE TITLE
filename change for executables in ghorg

### ISSUE THREAD

**Issue by AndriiOmelianenko** [gbloquel/asdf-ghorg#2]
```
$ asdf plugin-update ghorg
Updating ghorg to main
Already on 'main'
Your branch is up to date with 'origin/main'.

$ asdf install ghorg latest
* Downloading ghorg release 1.9.9...
curl: (22) The requested URL returned error: 404
asdf-ghorg: Could not download https://github.com/gabrie30/ghorg/releases/download/v1.9.9/ghorg_1.9.9_Darwin_arm64.tar.gz
```

https://github.com/gabrie30/ghorg/releases/tag/v1.9.9

seems in upstream project they changed the file names

**Comment by gbloquel** [comment]
Hi @AndriiOmelianenko ,

You are right the filename format for this release has been updated.
I have opened an issue on ghorg #https://github.com/gabrie30/ghorg/issues/342 

2 possibilities :
* either I change the version number for this delivery 
* or the author re-delivers with the same naming convention

**Comment by gbloquel** [comment]
The issue https://github.com/gabrie30/ghorg/issues/342 is closed and the binaries has been released.

The package in version 1.9.9 works
`<pre>asdf install ghorg latest
* Downloading ghorg release 1.9.9...
ghorg 1.9.9 installation was successful!</pre>`
